server:
  port: 8080
spring:
  application:
    name: cloud-consumer-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}