server:
  port: 80
spring:
  application:
    name: consumer-hystrix80
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://server1:7001/eureka,http://server2:7002/eureka
    instance:
      lease-expiration-duration-in-seconds: 10    # 10秒即过期
      lease-renewal-interval-in-seconds: 15       # 5秒一次心

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms=6s

