spring:
  application:
    name: spring-cloud-provider-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  type-aliases-package: cn.siwen.cloud.pojo
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8001
  spring:
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/
        #重启目录
        exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效


eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://server1:7001/eureka,http://server2:7002/eureka
    instance:
      lease-expiration-duration-in-seconds: 10    # 10秒即过期
      lease-renewal-interval-in-seconds: 15       # 5秒一次心
