server:
  port: 7001 #服务注册中心端口号
eureka:
  instance:
    hostname: server1 #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://server2:7002/eureka/
  enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
  eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）
